repositories {
    mavenCentral()
    google() // Needed for androidx
    maven { url = 'https://maven.brott.dev/' }
    maven { url = 'https://maven.pedropathing.com' }
    maven { url = "https://mymaven.bylazar.com/releases" }
    maven { url = 'https://repo.dairy.foundation/releases' }
    maven { url = 'https://jitpack.io' }
    maven { url = 'https://maven.anygeneric.dev/' }
}

dependencies {
    implementation 'org.firstinspires.ftc:Inspection:11.2.1'
    implementation 'org.firstinspires.ftc:Blocks:11.2.1'
    implementation 'org.firstinspires.ftc:RobotCore:11.2.1'
    implementation 'org.firstinspires.ftc:RobotServer:11.2.1'
    implementation 'org.firstinspires.ftc:OnBotJava:11.2.1'
    implementation 'org.firstinspires.ftc:Hardware:11.2.1'
    implementation 'org.firstinspires.ftc:FtcCommon:11.2.1'
    implementation 'org.firstinspires.ftc:Vision:11.2.1'
    implementation 'androidx.appcompat:appcompat:1.2.0'

    implementation "com.acmerobotics.dashboard:dashboard:0.5.1"

    implementation 'com.pedropathing:ftc:2.1.2'
    implementation 'com.pedropathing:telemetry:1.0.0'
    implementation 'com.bylazar:fullpanels:1.0.12'

//    implementation 'org.solverslib:photon:0.3.5'

    implementation "dev.anygeneric:blazeftc:0.1.36"
//    implementation 'dev.anygeneric:blazeftc_pedro:0.1.36'


    // Force Gradle to cap androidx.core at 1.13.1
    constraints {
        implementation("androidx.core:core:1.13.1") {
            because("Prevents transitive updates requiring Android API 37")
        }
        implementation("androidx.core:core-ktx:1.13.1") {
            because("Prevents transitive updates requiring Android API 37")
        }
    }
}

