plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.10.0'
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://repo.dairy.foundation/releases' }
        maven { url 'https://jitpack.io' }
        maven { url 'https://maven.brott.dev/' }
        maven { url 'https://maven.pedropathing.com' }
        maven { url "https://mymaven.bylazar.com/releases" }
    }
}

include ':FtcRobotController'
include ':TeamCode'
